# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Build Plugin Egg

on: [push]
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
    - name: Build and publish
      run: |
        python setup.py bdist_egg
    - uses: actions/upload-artifact@v2
      with:
        name: BatchRenamerRegEx-build
        path: dist/BatchRenamerRegEx-0.3.10-py2.7.egg
